#pragma once

inline void Lua_Register_Event(lua_State* const& L)
{
	Lua_NewMT(L, TypeNames<cocos2d::Event*>::value, TypeNames<cocos2d::Ref*>::value);

	Lua_NewFunc(L, "getCurrentTarget", [](lua_State* L)
	{
		auto&& t = Lua_ToTuple<cocos2d::Event*>(L, "getCurrentTarget error! need 1 args: self");
		auto&& r = std::get<0>(t)->getCurrentTarget();
		return Lua_Push(L, r);
	});

	Lua_NewFunc(L, "getType", [](lua_State* L)
	{
		auto&& t = Lua_ToTuple<cocos2d::Event*>(L, "getType error! need 1 args: self");
		auto&& r = std::get<0>(t)->getType();
		return Lua_Push(L, r);
	});

	lua_pop(L, 1);

	lua_pushstring(L, TypeNames<cocos2d::Event::Type>::value);
	lua_createtable(L, 7, 0);
	lua_pushstring(L, "TOUCH");	lua_pushinteger(L, (int)cocos2d::Event::Type::TOUCH);	lua_rawset(L, -3);
	lua_pushstring(L, "KEYBOARD");	lua_pushinteger(L, (int)cocos2d::Event::Type::KEYBOARD);	lua_rawset(L, -3);
	lua_pushstring(L, "ACCELERATION");	lua_pushinteger(L, (int)cocos2d::Event::Type::ACCELERATION);	lua_rawset(L, -3);
	lua_pushstring(L, "MOUSE");	lua_pushinteger(L, (int)cocos2d::Event::Type::MOUSE);	lua_rawset(L, -3);
	lua_pushstring(L, "FOCUS");	lua_pushinteger(L, (int)cocos2d::Event::Type::FOCUS);	lua_rawset(L, -3);
	lua_pushstring(L, "GAME_CONTROLLER");	lua_pushinteger(L, (int)cocos2d::Event::Type::GAME_CONTROLLER);	lua_rawset(L, -3);
	lua_pushstring(L, "CUSTOM");	lua_pushinteger(L, (int)cocos2d::Event::Type::CUSTOM);	lua_rawset(L, -3);
	lua_rawset(L, -3);

	lua_pushstring(L, TypeNames<cocos2d::EventKeyboard::KeyCode>::value);
	lua_createtable(L, 166, 0);
	lua_pushstring(L, "KEY_NONE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_NONE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PAUSE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PAUSE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SCROLL_LOCK"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SCROLL_LOCK);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PRINT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PRINT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SYSREQ"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SYSREQ);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_BREAK"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_BREAK);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_ESCAPE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_ESCAPE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_BACK"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_ESCAPE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_BACKSPACE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_BACKSPACE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_TAB"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_TAB);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_BACK_TAB"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_BACK_TAB);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RETURN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RETURN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPS_LOCK"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPS_LOCK);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SHIFT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SHIFT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_SHIFT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_SHIFT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_SHIFT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_SHIFT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CTRL"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CTRL);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_CTRL"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_CTRL);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_CTRL"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_CTRL);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_ALT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_ALT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_ALT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_ALT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_ALT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_ALT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_MENU"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_MENU);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_HYPER"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_HYPER);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_INSERT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_INSERT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_HOME"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_HOME);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PG_UP"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PG_UP);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DELETE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DELETE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_END"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_END);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PG_DOWN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PG_DOWN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_ARROW"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_ARROW);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_ARROW"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_ARROW);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_UP_ARROW"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_UP_ARROW);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DOWN_ARROW"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DOWN_ARROW);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_NUM_LOCK"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_NUM_LOCK);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_PLUS"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_PLUS);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_MINUS"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_MINUS);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_MULTIPLY"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_MULTIPLY);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_DIVIDE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_DIVIDE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_ENTER"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_ENTER);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_HOME"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_HOME);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_UP"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_UP);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_PG_UP"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_PG_UP);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_LEFT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_LEFT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_FIVE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_FIVE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_RIGHT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_RIGHT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_END"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_END);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_DOWN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_DOWN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_PG_DOWN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_PG_DOWN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_INSERT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_INSERT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_KP_DELETE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_KP_DELETE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F1"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F1);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F2"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F2);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F3"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F3);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F4"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F4);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F5"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F5);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F6"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F6);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F7"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F7);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F8"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F8);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F9"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F9);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F10"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F10);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F11"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F11);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F12"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F12);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SPACE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SPACE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_EXCLAM"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_EXCLAM);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_QUOTE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_QUOTE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_NUMBER"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_NUMBER);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DOLLAR"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DOLLAR);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PERCENT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PERCENT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CIRCUMFLEX"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CIRCUMFLEX);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_AMPERSAND"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_AMPERSAND);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_APOSTROPHE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_APOSTROPHE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_PARENTHESIS"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_PARENTHESIS);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_PARENTHESIS"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_PARENTHESIS);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_ASTERISK"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_ASTERISK);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PLUS"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PLUS);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_COMMA"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_COMMA);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_MINUS"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_MINUS);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PERIOD"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PERIOD);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SLASH"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SLASH);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_0"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_0);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_1"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_1);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_2"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_2);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_3"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_3);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_4"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_4);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_5"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_5);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_6"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_6);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_7"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_7);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_8"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_8);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_9"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_9);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_COLON"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_COLON);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SEMICOLON"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SEMICOLON);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LESS_THAN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LESS_THAN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_EQUAL"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_EQUAL);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_GREATER_THAN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_GREATER_THAN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_QUESTION"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_QUESTION);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_AT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_AT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_A"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_A);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_B"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_B);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_C"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_C);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_D"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_D);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_E"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_E);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_F"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_F);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_G"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_G);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_H"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_H);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_I"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_I);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_J"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_J);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_K"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_K);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_L"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_L);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_M"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_M);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_N"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_N);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_O"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_O);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_P"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_P);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_Q"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_Q);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_R"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_R);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_S"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_S);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_T"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_T);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_U"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_U);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_V"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_V);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_W"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_W);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_X"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_X);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_Y"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_Y);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_CAPITAL_Z"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_CAPITAL_Z);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_BRACKET"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_BRACKET);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_BACK_SLASH"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_BACK_SLASH);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_BRACKET"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_BRACKET);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_UNDERSCORE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_UNDERSCORE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_GRAVE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_GRAVE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_A"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_A);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_B"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_B);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_C"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_C);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_D"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_D);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_E"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_E);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_F"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_F);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_G"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_G);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_H"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_H);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_I"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_I);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_J"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_J);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_K"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_K);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_L"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_L);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_M"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_M);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_N"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_N);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_O"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_O);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_P"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_P);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_Q"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_Q);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_R"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_R);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_S"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_S);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_T"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_T);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_U"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_U);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_V"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_V);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_W"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_W);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_X"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_X);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_Y"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_Y);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_Z"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_Z);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_LEFT_BRACE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_LEFT_BRACE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_BAR"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_BAR);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_RIGHT_BRACE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_RIGHT_BRACE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_TILDE"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_TILDE);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_EURO"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_EURO);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_POUND"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_POUND);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_YEN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_YEN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_MIDDLE_DOT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_MIDDLE_DOT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_SEARCH"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_SEARCH);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DPAD_LEFT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DPAD_LEFT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DPAD_RIGHT"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DPAD_RIGHT);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DPAD_UP"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DPAD_UP);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DPAD_DOWN"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DPAD_DOWN);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_DPAD_CENTER"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_DPAD_CENTER);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_ENTER"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_ENTER);	lua_rawset(L, -3);
	lua_pushstring(L, "KEY_PLAY"); lua_pushinteger(L, (int)cocos2d::EventKeyboard::KeyCode::KEY_PLAY);	lua_rawset(L, -3);
	lua_rawset(L, -3);
}
